/**
 * Bulk import: column specs + validation rules.
 *
 * Single source of truth for BOTH the templates in /imports (generated by
 * scripts/generate-import-templates.js, which compiles this file) and the
 * import API/UI, so a column can never exist in one and not the other.
 *
 * Everything imports as NOT accepted: `status` is forced to 'pending' and is
 * deliberately not an importable column — a typo must never be able to approve
 * someone. Passwords are not set here either; they are generated and emailed
 * on approval (see mdfiles/acceptance-credentials-email.md).
 */
import { CHALLENGES } from './challenges';

export type EntityKey = 'teams' | 'participants' | 'mentors' | 'teams-with-leader';

export interface ColumnSpec {
  /** Exact Prisma field name — used verbatim as the CSV/Excel header. */
  key: string;
  labelAr: string;
  required: boolean;
  type: 'string' | 'boolean';
  /** Value must be one of these (case/space-insensitive) when provided. */
  oneOf?: readonly string[];
  /** A value outside `oneOf` warns instead of failing the row. */
  softOneOf?: boolean;
  note: string;
}

export const PROFESSIONAL_FIELDS = ['ذكاء اصناعي', 'علم البيانات', 'برمجة'] as const;
export const GENDERS = ['ذكر', 'أنثى'] as const;

export const IMPORT_SPECS: Record<EntityKey, { labelAr: string; columns: ColumnSpec[] }> = {
  teams: {
    labelAr: 'الفرق',
    columns: [
      { key: 'teamName', labelAr: 'اسم الفريق', required: true, type: 'string', note: 'فريد — وهو المفتاح الذي يربط المشاركين بالفريق' },
      { key: 'hackathonTrack', labelAr: 'المسار', required: true, type: 'string', oneOf: CHALLENGES, note: 'أحد المسارات الخمسة المعتمدة' },
      { key: 'ideaDescription', labelAr: 'وصف الفكرة', required: false, type: 'string', note: '' },
      { key: 'hearAboutUs', labelAr: 'من أين سمعت عنا', required: false, type: 'string', note: '' },
    ],
  },
  participants: {
    labelAr: 'المشاركون',
    columns: [
      { key: 'email', labelAr: 'البريد الإلكتروني', required: true, type: 'string', note: 'فريد' },
      { key: 'fullName', labelAr: 'الاسم كاملًا', required: true, type: 'string', note: '' },
      { key: 'contactNumber', labelAr: 'رقم التواصل', required: false, type: 'string', note: 'أرقام فقط' },
      { key: 'gender', labelAr: 'الجنس', required: false, type: 'string', oneOf: GENDERS, softOneOf: true, note: 'ذكر أو أنثى' },
      { key: 'isUniversityStudent', labelAr: 'طالب جامعي؟', required: false, type: 'boolean', note: 'TRUE أو FALSE' },
      { key: 'university', labelAr: 'الجامعة', required: false, type: 'string', note: '' },
      { key: 'universityMajor', labelAr: 'التخصص الجامعي', required: false, type: 'string', note: '' },
      { key: 'professionalField', labelAr: 'المجال المهني', required: false, type: 'string', oneOf: PROFESSIONAL_FIELDS, softOneOf: true, note: PROFESSIONAL_FIELDS.join(' | ') },
      { key: 'city', labelAr: 'المدينة / رابط Github', required: false, type: 'string', note: 'نموذج التسجيل العام يستخدم هذا الحقل لرابط Github' },
      { key: 'canAttendHackathon', labelAr: 'يستطيع الحضور؟', required: false, type: 'boolean', note: 'TRUE أو FALSE' },
      { key: 'teamName', labelAr: 'اسم الفريق', required: false, type: 'string', note: 'اتركه فارغاً للمشارك الفردي؛ وإلا يجب أن يكون الفريق موجوداً' },
      { key: 'isLeader', labelAr: 'قائد الفريق؟', required: false, type: 'boolean', note: 'TRUE لعضو واحد فقط في كل فريق' },
    ],
  },
  /**
   * One row = one team AND its leader. Creates both, links them, and marks the
   * participant as the leader — so a typical registration export can be
   * imported from a single file instead of two.
   */
  'teams-with-leader': {
    labelAr: 'الفرق مع القائد',
    columns: [
      { key: 'teamName', labelAr: 'اسم الفريق', required: true, type: 'string', note: 'فريد' },
      { key: 'hackathonTrack', labelAr: 'المسار', required: true, type: 'string', oneOf: CHALLENGES, note: 'أحد المسارات الخمسة المعتمدة' },
      { key: 'ideaDescription', labelAr: 'وصف الفكرة', required: false, type: 'string', note: '' },
      { key: 'hearAboutUs', labelAr: 'من أين سمعت عنا', required: false, type: 'string', note: '' },
      { key: 'leaderEmail', labelAr: 'بريد قائد الفريق', required: true, type: 'string', note: 'فريد — يُنشأ كمشارك وقائد للفريق' },
      { key: 'leaderFullName', labelAr: 'اسم قائد الفريق', required: true, type: 'string', note: '' },
      { key: 'leaderContactNumber', labelAr: 'رقم تواصل القائد', required: false, type: 'string', note: 'أرقام فقط' },
      { key: 'leaderGender', labelAr: 'جنس القائد', required: false, type: 'string', oneOf: GENDERS, softOneOf: true, note: 'ذكر أو أنثى' },
      { key: 'leaderIsUniversityStudent', labelAr: 'القائد طالب جامعي؟', required: false, type: 'boolean', note: 'TRUE أو FALSE' },
      { key: 'leaderUniversity', labelAr: 'جامعة القائد', required: false, type: 'string', note: '' },
      { key: 'leaderUniversityMajor', labelAr: 'تخصص القائد', required: false, type: 'string', note: '' },
      { key: 'leaderProfessionalField', labelAr: 'المجال المهني للقائد', required: false, type: 'string', oneOf: PROFESSIONAL_FIELDS, softOneOf: true, note: PROFESSIONAL_FIELDS.join(' | ') },
      { key: 'leaderCity', labelAr: 'مدينة القائد / رابط Github', required: false, type: 'string', note: '' },
      { key: 'leaderCanAttendHackathon', labelAr: 'القائد يستطيع الحضور؟', required: false, type: 'boolean', note: 'TRUE أو FALSE' },
    ],
  },
  mentors: {
    labelAr: 'الموجهون',
    columns: [
      { key: 'name', labelAr: 'الاسم', required: true, type: 'string', note: '' },
      { key: 'email', labelAr: 'البريد الإلكتروني', required: true, type: 'string', note: 'فريد' },
      { key: 'specialty', labelAr: 'التخصص', required: true, type: 'string', note: '' },
      { key: 'phone', labelAr: 'رقم الجوال', required: false, type: 'string', note: 'أرقام فقط' },
    ],
  },
};

export const headersFor = (entity: EntityKey): string[] =>
  IMPORT_SPECS[entity].columns.map((c) => c.key);

/** Loose truthy/falsey parsing so نعم/لا, 1/0 and TRUE/FALSE all work. */
export function parseBoolean(raw: string): boolean | null {
  const v = raw.trim().toLowerCase();
  if (v === '') return null;
  if (['true', '1', 'yes', 'y', 'نعم', 'صح'].includes(v)) return true;
  if (['false', '0', 'no', 'n', 'لا', 'خطأ'].includes(v)) return false;
  return null;
}
/** Distinguishes "not provided" from "provided but unparseable". */
export const isBooleanLike = (raw: string): boolean =>
  raw.trim() === '' || parseBoolean(raw) !== null;

export const normalizeEmail = (raw: string): string => raw.trim().toLowerCase();

export function isValidEmail(raw: string): boolean {
  const v = raw.trim();
  return v.length > 3 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
}
